// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvlve-do330fbnXPM1qJJUC4Fq5qyhThg',
    appId: '1:500785284766:web:d081e21b891e2630381d8f',
    messagingSenderId: '500785284766',
    projectId: 'buddygo-87468',
    authDomain: 'buddygo-87468.firebaseapp.com',
    databaseURL: 'https://buddygo-87468-default-rtdb.firebaseio.com',
    storageBucket: 'buddygo-87468.firebasestorage.app',
    measurementId: 'G-GPNR781Z73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG5v5rBqa4OzMyqQT-GkNV_ARJ78ECp-Q',
    appId: '1:500785284766:android:3cc887d3eabcb03f381d8f',
    messagingSenderId: '500785284766',
    projectId: 'buddygo-87468',
    databaseURL: 'https://buddygo-87468-default-rtdb.firebaseio.com',
    storageBucket: 'buddygo-87468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlc51mEoV8tT7pnBrZy5HCZks847cuEvA',
    appId: '1:500785284766:ios:10654bbb9d56fabe381d8f',
    messagingSenderId: '500785284766',
    projectId: 'buddygo-87468',
    databaseURL: 'https://buddygo-87468-default-rtdb.firebaseio.com',
    storageBucket: 'buddygo-87468.firebasestorage.app',
    iosClientId: '500785284766-sae1bb2ter7udcd8816u2hasg5jv89s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddygoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlc51mEoV8tT7pnBrZy5HCZks847cuEvA',
    appId: '1:500785284766:ios:10654bbb9d56fabe381d8f',
    messagingSenderId: '500785284766',
    projectId: 'buddygo-87468',
    databaseURL: 'https://buddygo-87468-default-rtdb.firebaseio.com',
    storageBucket: 'buddygo-87468.firebasestorage.app',
    iosClientId: '500785284766-sae1bb2ter7udcd8816u2hasg5jv89s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddygoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvlve-do330fbnXPM1qJJUC4Fq5qyhThg',
    appId: '1:500785284766:web:ed0bbb0803c172a8381d8f',
    messagingSenderId: '500785284766',
    projectId: 'buddygo-87468',
    authDomain: 'buddygo-87468.firebaseapp.com',
    databaseURL: 'https://buddygo-87468-default-rtdb.firebaseio.com',
    storageBucket: 'buddygo-87468.firebasestorage.app',
    measurementId: 'G-DBVQCBYCH9',
  );
}
